#!/bin/bash

# ---------------------------
#
# Common settings for all contexts.
#
# ---------------------------
#
# Prefix variables with MLKC_.
#
# ---------------------------

# Sets some env variables for the building process
export MLKC_DOCKER_IMAGE_TAG=holistic_hornet
export MLKC_GRASS_VERSION=7.8.5
export MLKC_GDAL_VERSION=3.2.2
export MLKC_NODE_VERSION=14.17.0
export MLKC_GRASS_INSTALL_FOLDER_SUFFIX=78
